---
title: "Mouse Cerebellum - Cell stats across GC pseudotime"
author: "Ioannis Sarropoulos"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(data.table)
  library(RColorBrewer)
  library(viridis)
})
```

```{r}
#1. Which lineage is to be processed?
lineage <- "GC"
```

```{r}
pseudotime_bins <- read_tsv(paste0("~/Mouse_Cereb/015_withinLineages/", lineage, "/Mouse_within", lineage, "_pseudotime_stats.txt"))

pseudotime_bins$pseudotime_bin_broad <- cut(x = pseudotime_bins$pseudotime, breaks = seq(0,1, by = 0.05),include.lowest = T, labels = F)

cell_stats <- readRDS("~/Mouse_Cereb/006_peaks/Mouse_Cerebellum_cellStats_byPeaks.rds")
```

```{r}
cell_stats <- left_join(cell_stats, pseudotime_bins)
```

Calculating a summary statistic per timepoint and pseudotime bin

```{r}
cell_stats$sample <- paste(cell_stats$pseudotime_bin_broad, cell_stats$timepoint, sep = "_")

cell_stats_sum <- filter(cell_stats, is.na(pseudotime)==F) %>%
  group_by(sample, timepoint, pseudotime_bin_broad) %>%
  summarise(
    ## Phastons in distal CREs (vertebrates)
    phastcons_dist_ci_low=Rmisc::CI(mean_phastcons_dist, ci = 0.95)[3],
    phastcons_dist_ci_mean=Rmisc::CI(mean_phastcons_dist, ci = 0.95)[2],
    phastcons_dist_ci_up=Rmisc::CI(mean_phastcons_dist, ci = 0.95)[1],
    ## Phastons in distal CREs (glires)
    phastcons_glires_dist_ci_low=Rmisc::CI(mean_phastcons_glires_dist, ci = 0.95)[3],
    phastcons_glires_dist_ci_mean=Rmisc::CI(mean_phastcons_glires_dist, ci = 0.95)[2],
    phastcons_glires_dist_ci_up=Rmisc::CI(mean_phastcons_glires_dist, ci = 0.95)[1],
    ## Pseudotime values within bin (control)
    pseudotime_ci_low=Rmisc::CI(pseudotime, ci = 0.95)[3],
    pseudotime_ci_mean=Rmisc::CI(pseudotime, ci = 0.95)[2],
    pseudotime_ci_up=Rmisc::CI(pseudotime, ci = 0.95)[1],
    ## Number of cells in each bin
    count=n())

ggplot(filter(cell_stats_sum, count > 20), aes(x=pseudotime_bin_broad, y=phastcons_dist_ci_mean, color=timepoint)) +
  geom_pointrange(aes(ymin=phastcons_dist_ci_low, ymax=phastcons_dist_ci_up)) +
  geom_line() +
  scale_x_continuous(breaks = 1:20) +
  scale_color_brewer(palette = "Spectral")+
  theme_classic() +
  ylab("Phastcons vertebrates (distal elements)")

ggplot(filter(cell_stats_sum, count > 20), aes(x=pseudotime_bin_broad, y=phastcons_glires_dist_ci_mean, color=timepoint)) +
  geom_pointrange(aes(ymin=phastcons_glires_dist_ci_low, ymax=phastcons_glires_dist_ci_up)) +
  geom_line() +
  scale_x_continuous(breaks = 1:20) +
  scale_color_brewer(palette = "Spectral")+
  theme_classic() +
  ylab("Phastcons glires (distal elements)")

ggplot(filter(cell_stats_sum, count > 20), aes(x=pseudotime_bin_broad, y=pseudotime_ci_mean, color=timepoint)) +
  geom_pointrange(aes(ymin=pseudotime_ci_low, ymax=pseudotime_ci_up)) +
  geom_line() +
  scale_x_continuous(breaks = 1:20) +
  scale_color_brewer(palette = "Spectral")+
  #scale_y_continuous(breaks = seq(0.4, 0.6, by = 0.02)) +
  theme_classic() +
  ylab("Pseudotime across bins")
```

Collectively, quantifying effect of differentiation and development fitting a linear model:

```{r}
m_full <- lm(mean_phastcons_dist ~ pseudotime + as.numeric(factor(timepoint)), data = cell_stats[is.na(cell_stats$pseudotime)==F,])

m_pseudo_only <- lm(mean_phastcons_dist ~ pseudotime, data = cell_stats[is.na(cell_stats$pseudotime)==F,])

m_dev_only <- lm(mean_phastcons_dist ~ as.numeric(factor(timepoint)), data = cell_stats[is.na(cell_stats$pseudotime)==F,])

anova(m_full, m_pseudo_only)
anova(m_full, m_dev_only)

coefficients(summary(m_full))
```

```{r}
m_full_glires <- lm(mean_phastcons_glires_dist ~ pseudotime + as.numeric(factor(timepoint)), data = cell_stats[is.na(cell_stats$pseudotime)==F,])

m_pseudo_only_glires <- lm(mean_phastcons_glires_dist ~ pseudotime, data = cell_stats[is.na(cell_stats$pseudotime)==F,])

m_dev_only_glires <- lm(mean_phastcons_glires_dist ~ as.numeric(factor(timepoint)), data = cell_stats[is.na(cell_stats$pseudotime)==F,])

anova(m_full_glires, m_pseudo_only_glires)
anova(m_full_glires, m_dev_only_glires)

coefficients(summary(m_full_glires))
```

```{r}
m_full_pseudo <- lm(mean_pseudotime ~ pseudotime + as.numeric(factor(timepoint)), data = cell_stats[is.na(cell_stats$pseudotime)==F,])

m_pseudo_only_pseudo <- lm(mean_pseudotime ~ pseudotime, data = cell_stats[is.na(cell_stats$pseudotime)==F,])

m_dev_only_pseudo <- lm(mean_pseudotime ~ as.numeric(factor(timepoint)), data = cell_stats[is.na(cell_stats$pseudotime)==F,])

anova(m_full_pseudo, m_pseudo_only_pseudo)
anova(m_full_pseudo, m_dev_only_pseudo)

coefficients(summary(m_full_pseudo))
```

We see an additive effect between pseudotime (differentiation/maturation) and developmental signal.

Export stats

```{r}
write_tsv(cell_stats_sum, paste0("~/Mouse_Cereb/015_withinLineages/", lineage, "/Mouse_within", lineage, "_cellStats_inPseudotimeBins.txt"))
```


```{r}
sessionInfo()
```

