---
title: "Vladoiu 2019 - make Seurat by stage"
author: "Ioannis Sarropoulos"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

````{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(data.table)
  library(Matrix)
  library(Seurat)
})
```

```{r}
setwd("/home/ioansarr/Mouse_Cereb/011_integrate_RNAseq/Vladoiu_2019")
vladoiu_anno <- read_tsv("Vladoiu_cell_type_annotation.txt")
```


```{r}
set.seed(1)

vladoiu_samples <- list.files("Vladoiu_data", pattern = "_matrix.mtx") %>% 
  gsub(pattern = "_matrix.mtx", replacement = "")

lapply(vladoiu_samples, function(x) {
  ## Reading in the data
  rna.data <- readMM(paste0("Vladoiu_data/",x,"_matrix.mtx"))
  colnames(rna.data) <- readLines(paste0("Vladoiu_data/",x,"_barcodes.tsv"))
  ## Adding the timepoint info to the barcodes
  vladoiu_t <- str_split(x, "_", simplify = T)[2]
  colnames(rna.data) <- paste(vladoiu_t, colnames(rna.data), sep = "_")
  ## Also stripping the "-1" ending
  colnames(rna.data) <- gsub("-1", "",colnames(rna.data))
  
  rna.genes <- read_tsv(paste0("Vladoiu_data/",x,"_genes.tsv"), col_names = F)
  row.names(rna.data) <- rna.genes$X1
  
  ## Processing with a standard Seurat pipeline (using SCTransform for scaling and variable gene detection)
  rna.seurat <- CreateSeuratObject(counts = rna.data)
  rna.seurat <- SCTransform(rna.seurat, verbose = F)
  
  rna.seurat <- RunPCA(rna.seurat, features = VariableFeatures(object = rna.seurat), npcs = 50, verbose = F)
  rna.seurat <- FindNeighbors(rna.seurat, dims = 1:50)
  rna.seurat <- FindClusters(rna.seurat, resolution = 0.5)
  rna.seurat <- RunUMAP(rna.seurat, dims = 1:50)
  
  ## Making cluster label a character to allow transfer
  vladoiu_anno$Vladoiu_cluster <- as.character(vladoiu_anno$Vladoiu_cluster)
  
  ## Adding metadata
  rna.seurat.metadata <- as.data.frame(rna.seurat@meta.data)
  rna.seurat.metadata$cell <- row.names(rna.seurat.metadata)
  rna.seurat.metadata <- left_join(rna.seurat.metadata, vladoiu_anno)
  
  rna.seurat$Vladoiu_cluster <- factor(rna.seurat.metadata$Vladoiu_cluster)
  rna.seurat$timepoint <-  rna.seurat.metadata$timepoint
  rna.seurat$Vladoiu_cell_type <-  factor(rna.seurat.metadata$Vladoiu_cell_type)
  
  saveRDS(rna.seurat, paste0("Vladoiu_rna_seurat/Vladoiu_", vladoiu_t, "_rna_seurat.rds"))
  return(NULL)
})

```

```{r}
sessionInfo()
```

