---
title: "Optimise downsampling for DA analysis"
author: "Ioannis Sarropoulos"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(data.table)
  library(ComplexHeatmap)
  library(UpSetR)
  library(RColorBrewer)
  library(viridis)
  library(DESeq2)
})
```

```{r, eval=FALSE}
gc_mat <- readRDS("~/Mouse_Cereb/012_devPeaks/byCellType/GC/GC_matrix_pseudobulk_byLib.rds")

samples <- colnames(gc_mat)[grepl("P14|P63", colnames(gc_mat))]

colSums(gc_mat[,samples])

gc_late <- gc_mat[grepl("chrX|chrY", row.names(gc_mat)) ==F,samples]

dim(gc_late)
colSums(gc_late)

atac.info <- data.frame(sample=samples, stringsAsFactors = F) %>%
  separate(sample, into = c("timepoint", "lib", "sex"), remove = F) %>%
  group_by(timepoint) %>%
  mutate(rep=1:n()) %>%
  ungroup()

subsampleDEseq <- function(mat, nReads) {
  ## Create sample matrix
  sub_mat <- Reduce(full_join, lapply(colnames(mat), function(s) {
  set.seed(1)
  subs <- sample(names(mat[,s]),
                 size = nReads,
                 prob = mat[,s]/sum(mat[,s]),
                 replace = T)
  count.df <- data.frame(peak=names(table(subs)), count=as.numeric(table(subs)), stringsAsFactors = F)
  colnames(count.df)[2] <- s
  return(count.df)
})) %>%
  right_join(data.frame(peak=row.names(mat), stringsAsFactors = F)) %>%
  column_to_rownames("peak")

  sub_mat[is.na(sub_mat)] <- 0
  
  ## Now running DEseq
}


```


```{r, eval=FALSE}
subsample_mat <- function(mat, nReads, seed=1) {
  ## Create sample matrix
  sub_mat <- Reduce(full_join, lapply(colnames(mat), function(s) {
  set.seed(seed)
  subs <- sample(names(mat[,s]),
                 size = nReads,
                 prob = mat[,s]/sum(mat[,s]),
                 replace = T)
  count.df <- data.frame(peak=names(table(subs)), count=as.numeric(table(subs)), stringsAsFactors = F)
  colnames(count.df)[2] <- s
  return(count.df)
})) %>%
  right_join(data.frame(peak=row.names(mat), stringsAsFactors = F)) %>%
  column_to_rownames("peak")

  sub_mat[is.na(sub_mat)] <- 0
  return(sub_mat)
}

runDeseq <- function(mat,info=atac.info) {
  deseq_obj <- DESeqDataSetFromMatrix(countData = mat,
                                     colData = info[info$sample %in% colnames(mat),],
                                     design = ~ timepoint)

  deseq_obj <- DESeq(deseq_obj)
  res <- results(deseq_obj, contrast=c("timepoint", unique(info$timepoint)[2], unique(info$timepoint)[1]), alpha = 0.05, lfcThreshold = 0.5)
  return(res)
}
```

Running the subsampling for multiple sequencing depths

```{r, eval=FALSE}
seq_depths <- c(0.1, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 7, 8, 9, 10,15, 20, 30, 40, 50, 100) * 1e6

deseq_sim <- Reduce(bind_rows,lapply(1:10, function(s) {
  sim.df <- Reduce(bind_rows,lapply(seq_depths, function(n) {
  ## Subsample
  m <- subsample_mat(gc_late, n, s)
  ## Correlation with full bulk
  c_mat <- cor(m, gc_late, method = "spearman")
  c <- mean(diag(c_mat))
  ## Runnning deseq
  d <- runDeseq(m)
  ## Counting DA peaks
  d_df <- data.frame(padj=d$padj, log2FoldChange=d$log2FoldChange,stringsAsFactors = F) %>%
    filter(is.na(padj)==F, is.na(log2FoldChange)==F)
  n_up <- sum(d_df$padj < 0.05 & d_df$log2FoldChange > 0.5)
  n_down <- sum(d_df$padj < 0.05 & d_df$log2FoldChange < (-0.5))
  n_tested <- length(d$padj)
  up_meanFC  <- mean(d_df$log2FoldChange[d_df$padj < 0.05 & d_df$log2FoldChange > 0.5])
  down_meanFC  <- mean(d_df$log2FoldChange[d_df$padj < 0.05 & d_df$log2FoldChange < (-0.5)])
  return(data.frame(nReads=n, 
                    cor=c,
                    n_up,
                    n_down,
                    n_tested,
                    up_meanFC,
                    down_meanFC,
                    stringsAsFactors = F))
}))
  sim.df$seed <- s
  return(sim.df)
}))


```

```{r, eval=FALSE}
write_tsv(deseq_sim, "~/Mouse_Cereb/012_devPeaks/byCellType_subsampled/GC_P14-P63_subsampling_stats.txt")
```

```{r}
deseq_sim <- read_tsv("~/Mouse_Cereb/012_devPeaks/byCellType_subsampled/GC_P14-P63_subsampling_stats.txt")

deseq_sim$seed <- factor(deseq_sim$seed)
```


```{r}
ggplot(deseq_sim, aes(x=nReads, y=cor, color=seed)) +
  geom_point() +
  geom_hline(yintercept = 0.95, color="red", lty="dashed") +
  geom_vline(xintercept = 4e6, color="red", lty="dashed") +
  geom_line()

ggplot(deseq_sim, aes(x=nReads, y=log10(n_up + 1), color=seed)) +
  geom_point() +
    geom_vline(xintercept = 4e6, color="red", lty="dashed") +
  geom_line()

ggplot(deseq_sim, aes(x=nReads, y=n_up, color=seed)) +
  geom_point() +
  geom_vline(xintercept = 4e6, color="red", lty="dashed") +
  geom_line()

ggplot(deseq_sim, aes(x=nReads, y=log10(n_down + 1), color=seed)) +
  geom_point() +
  geom_line()

ggplot(deseq_sim, aes(x=nReads, y=n_down, color=seed)) +
  geom_point() +
  geom_vline(xintercept = 4e6, color="red", lty="dashed") +
  geom_line()

ggplot(deseq_sim, aes(x=nReads, y=up_meanFC, color=seed)) +
  geom_point() +
  geom_line()

ggplot(deseq_sim, aes(x=nReads, y=down_meanFC, color=seed)) +
  geom_point() +
  geom_line()
```

```{r, fig.width=6, fig.height=4}
deseq_sim$n_da <- deseq_sim$n_up + deseq_sim$n_down

p <- ggplot(deseq_sim, aes(x=log10(nReads), y=log10(n_da + 1), color=seed)) +
  geom_point() +
  scale_color_brewer(palette = "Paired") +
  ylab("Number of DA peaks (log10)") +
  xlab("Number of fragments per sample (log10)") +
  geom_vline(xintercept = log10(4e6), color="red", lty="dashed") +
  geom_line() +
  theme_classic()

p

pdf("~/Mouse_Cereb/Figures/004_devPeaks/Mouse_GC_late_downsampling_DApeaks.pdf", width = 6, height = 4, useDingbats = F); print(p);dev.off()

p <- ggplot(deseq_sim, aes(x=log10(nReads), y=cor, color=seed)) +
  geom_point() +
  scale_color_brewer(palette = "Paired", name="Simulation") +
  ylab("Correlation with full library (Spearman's rho)") +
  xlab("Number of fragments per sample (log10)") +
  geom_vline(xintercept = log10(4e6), color="red", lty="dashed") +
  geom_hline(yintercept = 0.95, color="red", lty="dashed") +
  geom_line() +
  theme_classic()

p

pdf("~/Mouse_Cereb/Figures/004_devPeaks/Mouse_GC_late_downsampling_Correlation_withFull.pdf", width = 6, height = 4, useDingbats = F); print(p);dev.off()
```


```{r}
sessionInfo()
```

