---
title: "DevPeaks byCellType: 4Mreads perSample"
author: "Ioannis Sarropoulos"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(data.table)
  library(ComplexHeatmap)
  library(UpSetR)
  library(RColorBrewer)
  library(viridis)
  library(DESeq2)
})
```

```{r}
options(scipen = 999)
ct <- c("Astroglia", "GABA_DN", "Glut_DN","PC", "Interneuron", "GC")
nR <- 4e6
```

Loading peak matrix

```{r}
peak_mat <- readRDS("~/Mouse_Cereb/006_peaks/Mouse_Cerebellum_reproducible_peak_matrix_SE_withInfo_robustPeaks.rds")
mouse_peaks <- read.table("~/Mouse_Cereb/006_peaks/Mouse_Cerebellum_reproducible_peaks_summary.txt", header = T, sep = "\t", stringsAsFactors = F)
cell_anno <- readRDS("~/Mouse_Cereb/004_cellTypes_broad/Mouse_Cerebellum_atac_finalCellType_annotation.rds")
```

Preparing some metadata

```{r}
samples <- sort(unique(peak_mat$Sample_short))

print(samples)

atac.info <- data.frame(sample=samples, stringsAsFactors = F) %>%
  separate(sample, into = c("timepoint", "lib", "sex"), remove = F) %>%
  group_by(timepoint) %>%
  mutate(rep=1:n()) %>%
  ungroup()

timepoints <- unique(atac.info$timepoint)
```

Functions needed

```{r}
makePseudobulk <- function(cell_type) {
  atac.pseudobulk <- do.call(cbind, lapply(samples, function(s) {
  cell_i <- which(peak_mat@colData$Sample_short==s & peak_mat$cellNames_short %in% cell_anno$cellNames_short[cell_anno$Cell_type_broad==cell_type])
  atac.data <- assay(peak_mat[,cell_i])
  return(Matrix::rowSums(atac.data))
  }))
  colnames(atac.pseudobulk) <- samples
  rownames(atac.pseudobulk) <- peak_mat@elementMetadata$peak
  return(atac.pseudobulk)
}

subsample_mat <- function(mat, nReads) {
  ## Create sample matrix
  sub_mat <- Reduce(full_join, lapply(colnames(mat), function(s) {
  set.seed(1)
  subs <- sample(names(mat[,s]),
                 size = nReads,
                 prob = mat[,s]/sum(mat[,s]),
                 replace = T)
  count.df <- data.frame(peak=names(table(subs)), count=as.numeric(table(subs)), stringsAsFactors = F)
  colnames(count.df)[2] <- s
  return(count.df)
})) %>%
  right_join(data.frame(peak=row.names(mat), stringsAsFactors = F)) %>%
  column_to_rownames("peak")

  sub_mat[is.na(sub_mat)] <- 0
  return(sub_mat)
}
```

```{r}
lapply(ct, function(cell_type) {
  mat <- makePseudobulk(cell_type = cell_type)
  saveRDS(mat, paste0("~/Mouse_Cereb/012_devPeaks/byCellType_subsampled/", cell_type, "_matrix_pseudobulk_byLib_all.rds"))
  ## Excluding sex chromosomes
  mat <- mat[grepl("chrX|chrY", row.names(mat)) ==F,]
  ## Keeping only pseudobulks with at least the number of reads we want to subsample!
  mat <- mat[, colSums(mat) > nR]
  
  if (ncol(mat)<4) {
    return(NULL)
  } else {
     ## Also checking that both replicates passed the test, otherwise remove the remaining one
  timepoint_counts <- table(sapply(colnames(mat), function(x) str_split(x, "_",simplify = T)[1]))

  t <- names(timepoint_counts)[timepoint_counts > 1]

  mat <- mat[, grepl(paste(paste0(t, "_"), collapse = "|"), colnames(mat))]
  
  if (ncol(mat)<4) {
    return(NULL)
  } else {
  ## Subsampling to X number of reads
  sub_mat <- subsample_mat(mat, nR)
  saveRDS(mat, paste0("~/Mouse_Cereb/012_devPeaks/byCellType_subsampled/", cell_type, "_matrix_pseudobulk_byLib_sub_", nR, "_reads.rds"))
  ## Now constructing a DESEq object
  cellType.deseq <- DESeqDataSetFromMatrix(countData = sub_mat,
                                     colData = atac.info[atac.info$sample %in% colnames(sub_mat),],
                                     design = ~ timepoint)

  cellType.deseq <- DESeq(cellType.deseq)
  saveRDS(cellType.deseq, paste0("~/Mouse_Cereb/012_devPeaks/byCellType_subsampled/", cell_type, "_pseudobulk_byTimepoint_sub_", nR, "_reads_deseq.rds"))
  
  ## Processing the results
  cellType.timepoints <- unique(atac.info$timepoint[atac.info$sample %in% colnames(sub_mat)])

  lapply(1:(length(cellType.timepoints)-1), function(i) {
  plotMA(cellType.deseq, contrast=c("timepoint",cellType.timepoints[i], cellType.timepoints[i+1]))
  })

  cellType.deseq.res <- data.frame(peak=row.names(cellType.deseq), stringsAsFactors = F)
  
  getDeseqRes <- function(deseqObj, s1, s2, slot="timepoint") {
    res <- results(deseqObj, contrast=c("timepoint", s2, s1), alpha = 0.05, lfcThreshold = 0.5)
    cellType.deseq.res[, paste(s1, s2, sep = "_")] <<- ifelse(res$padj < 0.05 & abs(res$log2FoldChange) > 0.5,
                     yes = ifelse(res$log2FoldChange > 0,
                                  yes = "up",
                                  no = "down"),
                     no="no")
  #cellType.deseq.res <<- left_join(cellType.deseq.res, select(res, peak, paste(s1, s2, sep = "-")))
  return(res)
}

  cellType.deseq.res_list <- lapply(1:(length(cellType.timepoints)-1), function(t) getDeseqRes(cellType.deseq, cellType.timepoints[t], cellType.timepoints[t+1]))
cellType.deseq.res[is.na(cellType.deseq.res)] <- "not-tested"

  saveRDS(cellType.deseq.res_list, paste0("~/Mouse_Cereb/012_devPeaks/byCellType_subsampled/", cell_type, "_pseudobulk_byTimepoint_sub_", nR, "_reads_deseq_results_list.rds"))

  saveRDS(cellType.deseq.res, paste0("~/Mouse_Cereb/012_devPeaks/byCellType_subsampled/", cell_type, "_pseudobulk_byTimepoint_sub_", nR, "_reads_deseq_results.rds"))

  cellType.deseq.res.gather <- gather(cellType.deseq.res, -peak, key = "timepoint", value = "sign", na.rm = F) %>%
  filter(sign %in% c("up", "down")) %>%
  group_by(timepoint, sign, .drop = FALSE) %>%
    dplyr::count() %>%
  ungroup()

  cellType.deseq.res.gather$timepoint <- factor(cellType.deseq.res.gather$timepoint, levels = sapply(1:(length(cellType.timepoints)-1), function(t) paste(cellType.timepoints[t], cellType.timepoints[t+1], sep = "_")))

  cellType.deseq.res.gather$stage <- as.integer(cellType.deseq.res.gather$timepoint)

  p <- ggplot(cellType.deseq.res.gather, aes(x=stage, y=n, color=sign)) +
  geom_point() +
  geom_line(lwd = 0.8) +
  scale_x_continuous(breaks = unique(cellType.deseq.res.gather$stage), labels=unique(cellType.deseq.res.gather$timepoint)) +
  scale_color_manual(values = c("indianred", "deepskyblue3")) +
  theme_classic() +
  ylab("Number of DA regions") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank()) +
  ggtitle(cell_type)

  p

  pdf(paste0("~/Mouse_Cereb/Figures/004_devPeaks/byCellType_subsampled/Mouse_peaks_", cell_type, "_deseq_byStage_sub_", nR, "_reads.pdf"), width = 6, height = 4, useDingbats = F); print(p); dev.off()
  }
  }
})
```

```{r}
sessionInfo()
```
