---
title: "Mouse CREs associated with TFs"
author: "Ioannis Sarropoulos"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(data.table)
  library(viridis)
  library(SummarizedExperiment)
  library(RColorBrewer)
})
```

```{r}
## Mouse peak info
mouse_peaks <- read.table("~/Mouse_Cereb/006_peaks/Mouse_Cerebellum_reproducible_peaks_summary.txt", header = T, sep = "\t", stringsAsFactors = F)

## All peak2gene connections
peak2gene <- readRDS("~/Mouse_Cereb/Revisions/002_cre2gene_assignment/CRE_to_gene_assignment_sigInteractions.rds")
```

## Number of CREs per gene

Let's proceed by generating stats per gene

```{r}
gene.stats <- left_join(peak2gene, mouse_peaks) %>%
  group_by(gene) %>%
  summarise(nPeaks=n_distinct(peak),
            nDistal=n_distinct(peak[genomic_class_broad %in% c("Distal")]),
            phastcons_dist=mean(meanPhastCons_100bp[genomic_class_broad %in% c("Distal")]),
            minAge_dist=mean(min_age_num[genomic_class_broad %in% c("Distal")]))


plot(sort(gene.stats$nPeaks))
plot(sort(gene.stats$nDistal))

hist(gene.stats$phastcons_dist)
hist(gene.stats$minAge_dist)
```

```{r}
tfs <- read_tsv("~/Resources/Transcription_Factors/Mus_musculus_TF.txt")

tfs <- dplyr::rename(tfs, gene=Symbol, TF_family=Family)
gene.stats <- left_join(gene.stats, tfs)
```

```{r, fig.width=2, fig.height=4}
p <- ggplot(gene.stats, aes(x=is.na(TF_family)==F, y=phastcons_dist, fill=is.na(TF_family)==F))+
  geom_boxplot(notch = T) +
  scale_fill_manual(values = c("gray70", "deepskyblue3"), guide=F) +
  scale_x_discrete(labels=c("Other", "TF"), name=NULL) +
  ylab("Phastcons vertebrates (mean distal CREs)") +
  theme_classic()

p

wilcox.test(gene.stats$phastcons_dist[is.na(gene.stats$TF_family)==F],
            gene.stats$phastcons_dist[is.na(gene.stats$TF_family)==T])

pdf("~/Mouse_Cereb/Revisions/Figures/007_PhastCons_TF_CREs.pdf", width = 2, height = 4, useDingbats = F); print(p); dev.off()

p <- ggplot(gene.stats, aes(x=is.na(TF_family)==F, y=minAge_dist, fill=is.na(TF_family)==F))+
  geom_boxplot(notch = T)+
  scale_fill_manual(values = c("gray70", "deepskyblue3"), guide=F) +
  scale_x_discrete(labels=c("Other", "TF"), name=NULL) +
  ylab("Minimum age (mean distal CREs)") +
  theme_classic()

p

wilcox.test(gene.stats$minAge_dist[is.na(gene.stats$TF_family)==F],
            gene.stats$minAge_dist[is.na(gene.stats$TF_family)==T])

pdf("~/Mouse_Cereb/Revisions/Figures/007_MinimumAge_TF_CREs.pdf", width = 2, height = 4, useDingbats = F); print(p); dev.off()
```

```{r}
sessionInfo()
```

