---
title: "phastCons placental mammals"
author: "Ioannis Sarropoulos"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(RColorBrewer)
  library(viridis)
  library(ComplexHeatmap)
  library(data.table)
})
```

```{r}
peaks <- read.table("~/Mouse_Cereb/006_peaks/Mouse_Cerebellum_reproducible_peaks_summary.txt", header = T, sep = "\t", stringsAsFactors = F)

peak_sliding_windows <- read.table("~/Mouse_Cereb/006_peaks/001_peak_annotation/phastCons/Mouse_Cerebellum_peaks_final_100bp_windows_10bp_step.bed", header = F, sep = "\t", stringsAsFactors = F)
colnames(peak_sliding_windows) <- c("chr", "start", "end", "window_name")
```


Calculating average phastCons score for each window:

```{bash}
~/Software/utils/bigWigAverageOverBed ~/Mouse_Cereb/006_peaks/001_peak_annotation/phastCons/mm10.60way.phastCons60wayPlacental.bw ~/Mouse_Cereb/006_peaks/001_peak_annotation/phastCons/Mouse_Cerebellum_peaks_final_100bp_windows_10bp_step.bed ~/Mouse_Cereb/006_peaks/001_peak_annotation/phastCons/Mouse_Cerebellum_peaks_100bp_windows_phastCons_placental.txt -minMax
```

Reading in the results:

```{r}
phastcons_windows <- read_tsv("~/Mouse_Cereb/006_peaks/001_peak_annotation/phastCons/Mouse_Cerebellum_peaks_100bp_windows_phastCons_placental.txt", col_names = F)

## The column of interest is X6 (mean0, i.e.counting non-covered bases as 0)
phastcons_windows_sum <- mutate(phastcons_windows, peak=gsub("_[0-9]*$", "", X1)) %>%
  group_by(peak) %>%
  summarise(meanPhastCons_Placental_100bp=max(X6), mostCons100bp_window=X1[which.max(X6)])

## Getting the info about the most conserved region:
phastcons_windows_sum <- left_join(phastcons_windows_sum, dplyr::rename(peak_sliding_windows,mostCons100bp_window=window_name))

phastcons_windows_sum$mostCons100bp_Placental <- paste(phastcons_windows_sum$chr, phastcons_windows_sum$start, phastcons_windows_sum$end, sep = "_")

peaks <- left_join(peaks, select(phastcons_windows_sum, peak, meanPhastCons_Placental_100bp, mostCons100bp_Placental))
```

```{r}
cor(peaks$meanPhastCons_100bp, peaks$meanPhastCons_Placental_100bp)
cor(peaks$meanPhastCons_100bp, peaks$meanPhastCons_Glires_100bp)
```

```{r}
p <- ggplot(peaks, aes(x=genomic_class, y=meanPhastCons_Placental_100bp, fill=genomic_class_broad)) +
  geom_violin(alpha=0.5) +
  geom_boxplot(notch = T, width=0.2, outlier.alpha = 0) +
  theme_classic() +
  xlab("") +
  ylab("PhastCons (placental)") +
  scale_fill_manual(values = c("darkorange2", "deepskyblue3", "darkolivegreen3","darkorchid"), name="Broad\nGenomic\nClass") +
  theme(axis.text.x = element_text(angle=45, hjust = 0.95))

p

pdf("~/Mouse_Cereb/Figures/003_peakAnnotation/Mouse_peaks_phastCons_placentals_byGenomicClass.pdf", width = 8, height = 5, useDingbats = F); print(p); dev.off()
```

```{r}
write_tsv(select(peaks, peak, meanPhastCons_Placental_100bp,  mostCons100bp_Placental), "~/Mouse_Cereb/006_peaks/Mouse_Cerebellum_peaks_summary_placentalPhastCons.txt")
```

Now we can calculate per cell stats (using robust distal CREs) - both all and for different age groups.

```{r}
peak_mat <- readRDS("~/Mouse_Cereb/006_peaks/Mouse_Cerebellum_reproducible_peak_matrix_SE_withInfo_robustPeaks.rds")
```

```{r}
clust <- sort(unique(peak_mat@colData$Clusters_finalNucSet_res1.5))

cell.stats <- Reduce(bind_rows, lapply(clust, function(id) {
  print(paste0("Preparing matrix for: ", id))
  cell_i <- which(peak_mat@colData$Clusters_finalNucSet_res1.5==id)
  atac.data <- assay(peak_mat[,cell_i])
  row.names(atac.data) <- peak_mat@elementMetadata$peak
  summ <- Matrix::summary(atac.data)
  atac.data.tidy <- data.frame(peak = rownames(atac.data)[summ$i],
           cell = colnames(atac.data)[summ$j],
           count = summ$x, stringsAsFactors = F)
  atac.data.tidy <- left_join(atac.data.tidy, select(peaks, peak, genomic_class, genomic_class_broad,  meanPhastCons_Placental_100bp, min_age_num))
  print(paste0("Generating stats for: ", id))
  cell.stats <- group_by(atac.data.tidy, cell) %>%
  summarise(mean_phastcons_Placental_dist = mean(meanPhastCons_Placental_100bp[genomic_class_broad %in% c("Distal")]),
             mean_phastcons_Placental_dist_20 = mean(meanPhastCons_Placental_100bp[genomic_class_broad %in% c("Distal") & min_age_num==20]),
  mean_phastcons_Placental_dist_90 = mean(meanPhastCons_Placental_100bp[genomic_class_broad %in% c("Distal") & min_age_num==90]),
  mean_phastcons_Placental_dist_105 = mean(meanPhastCons_Placental_100bp[genomic_class_broad %in% c("Distal") & min_age_num==105]),
    mean_phastcons_Placental_dist_160 = mean(meanPhastCons_Placental_100bp[genomic_class_broad %in% c("Distal") & min_age_num==160]),
  mean_phastcons_Placental_dist_177 = mean(meanPhastCons_Placental_100bp[genomic_class_broad %in% c("Distal") & min_age_num==177]),
  mean_phastcons_Placental_dist_312 = mean(meanPhastCons_Placental_100bp[genomic_class_broad %in% c("Distal") & min_age_num==312]),
  mean_phastcons_Placental_dist_435 = mean(meanPhastCons_Placental_100bp[genomic_class_broad %in% c("Distal") & min_age_num==435]),
            total=n(),
            count_sum=sum(count))
  return(cell.stats)
}))
```


```{r}
saveRDS(cell.stats, "~/Mouse_Cereb/Revisions/007_conservation_backgroundDist/Mouse_phastcons_Placentals_cell_stats_byAge_distalOnly.rds")
```

```{r}
cell_anno <- readRDS("~/Mouse_Cereb/004_cellTypes_broad/Mouse_Cerebellum_atac_finalCellType_annotation.rds")

cell.stats <- left_join(cell_anno, cell.stats)
```

```{r}
cell_lineage_stats <- filter(cell.stats, !Cell_type_broad %in% c("Parabrachial+Isthmic_nuclei", "Glut_DN+Isthmic_nuclei", "Other")) %>%
  group_by(Cell_type_broad, Cell_type_broad_color, Timepoint, Lib) %>%
  summarise(
    mean_phastcons_Placental_dist=mean(mean_phastcons_Placental_dist),
    mean_phastcons_Placental_dist_20=mean(mean_phastcons_Placental_dist_20),
    mean_phastcons_Placental_dist_90=mean(mean_phastcons_Placental_dist_90),
    mean_phastcons_Placental_dist_105=mean(mean_phastcons_Placental_dist_105),
    mean_phastcons_Placental_dist_160=mean(mean_phastcons_Placental_dist_160),
    mean_phastcons_Placental_dist_177=mean(mean_phastcons_Placental_dist_177),
    mean_phastcons_Placental_dist_312=mean(mean_phastcons_Placental_dist_312),
    mean_phastcons_Placental_dist_435=mean(mean_phastcons_Placental_dist_435),
    ## Number of cells in each bin
    count=n()) %>%
  ungroup() %>%
  group_by(Cell_type_broad, Cell_type_broad_color, Timepoint) %>%
  summarise(
    phastcons_Placental_dist_all_ci_up=max(mean_phastcons_Placental_dist),
    phastcons_Placental_dist_all_ci_mean=mean(mean_phastcons_Placental_dist),
    phastcons_Placental_dist_all_ci_low=min(mean_phastcons_Placental_dist),
    
    phastcons_Placental_dist_20_ci_up=max(mean_phastcons_Placental_dist_20),
    phastcons_Placental_dist_20_ci_mean=mean(mean_phastcons_Placental_dist_20),
    phastcons_Placental_dist_20_ci_low=min(mean_phastcons_Placental_dist_20),
    
    phastcons_Placental_dist_90_ci_up=max(mean_phastcons_Placental_dist_90),
    phastcons_Placental_dist_90_ci_mean=mean(mean_phastcons_Placental_dist_90),
    phastcons_Placental_dist_90_ci_low=min(mean_phastcons_Placental_dist_90),
    
    phastcons_Placental_dist_105_ci_up=max(mean_phastcons_Placental_dist_105),
    phastcons_Placental_dist_105_ci_mean=mean(mean_phastcons_Placental_dist_105),
    phastcons_Placental_dist_105_ci_low=min(mean_phastcons_Placental_dist_105),
    
    phastcons_Placental_dist_160_ci_up=max(mean_phastcons_Placental_dist_160),
    phastcons_Placental_dist_160_ci_mean=mean(mean_phastcons_Placental_dist_160),
    phastcons_Placental_dist_160_ci_low=min(mean_phastcons_Placental_dist_160),
    
    phastcons_Placental_dist_177_ci_up=max(mean_phastcons_Placental_dist_177),
    phastcons_Placental_dist_177_ci_mean=mean(mean_phastcons_Placental_dist_177),
    phastcons_Placental_dist_177_ci_low=min(mean_phastcons_Placental_dist_177),
    
    phastcons_Placental_dist_312_ci_up=max(mean_phastcons_Placental_dist_312),
    phastcons_Placental_dist_312_ci_mean=mean(mean_phastcons_Placental_dist_312),
    phastcons_Placental_dist_312_ci_low=min(mean_phastcons_Placental_dist_312),
       
    phastcons_Placental_dist_435_ci_up=max(mean_phastcons_Placental_dist_435),
    phastcons_Placental_dist_435_ci_mean=mean(mean_phastcons_Placental_dist_435),
    phastcons_Placental_dist_435_ci_low=min(mean_phastcons_Placental_dist_435),
    
    count=sum(count)
    
  )

cell_lineage_stats$t <- as.numeric(factor(cell_lineage_stats$Timepoint))
cell_lineage_stats <- droplevels(cell_lineage_stats)

cell_lineage_stats_major <- filter(cell_lineage_stats, !Cell_type_broad %in% c("Isthmic_nuclei", "MBO", "Parabrachial")) %>%
  droplevels()
```


```{r}
p <- ggplot(filter(cell_lineage_stats_major, count >=50), aes(x=t, y= phastcons_Placental_dist_all_ci_mean, color=Cell_type_broad)) +
  geom_pointrange(aes(ymin=phastcons_Placental_dist_all_ci_low, ymax= phastcons_Placental_dist_all_ci_up)) +
  geom_line() +
  scale_x_continuous(breaks = seq(min(cell_lineage_stats_major$t), max(cell_lineage_stats_major$t), by = 1), labels=sort(unique(cell_lineage_stats_major$Timepoint))) +
  scale_color_manual(values = levels(cell_lineage_stats_major$Cell_type_broad_color)) +
  #scale_y_continuous(breaks = seq(0.4, 0.6, by = 0.02)) +
  theme_classic() +
  ylab("Phastcons placentals (distal CREs)") +
    xlab("Developmental stage") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank())

p

pdf("~/Mouse_Cereb/Revisions/Figures/007_Mouse_cerebellum_CellTypesBroad_distal_phastCons_Placentals.pdf", width = 6, height = 4, useDingbats = F); print(p); dev.off()
```


```{r}
p <- ggplot(filter(cell_lineage_stats_major, count >=50), aes(x=t, y= phastcons_Placental_dist_177_ci_mean, color=Cell_type_broad)) +
  geom_pointrange(aes(ymin=phastcons_Placental_dist_177_ci_low, ymax= phastcons_Placental_dist_177_ci_up)) +
  geom_line() +
  scale_x_continuous(breaks = seq(min(cell_lineage_stats_major$t), max(cell_lineage_stats_major$t), by = 1), labels=sort(unique(cell_lineage_stats_major$Timepoint))) +
  scale_color_manual(values = levels(cell_lineage_stats_major$Cell_type_broad_color)) +
  #scale_y_continuous(breaks = seq(0.4, 0.6, by = 0.02)) +
  theme_classic() +
  ylab("Phastcons placentals (distal CREs, 177 Mya)") +
    xlab("Developmental stage") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank())

p

pdf("~/Mouse_Cereb/Revisions/Figures/007_Mouse_cerebellum_CellTypesBroad_distal_177Mya_phastCons_Placentals.pdf", width = 6, height = 4, useDingbats = F); print(p); dev.off()
```

```{r}
p <- ggplot(filter(cell_lineage_stats_major, count >=50), aes(x=t, y= phastcons_Placental_dist_160_ci_mean, color=Cell_type_broad)) +
  geom_pointrange(aes(ymin=phastcons_Placental_dist_160_ci_low, ymax= phastcons_Placental_dist_160_ci_up)) +
  geom_line() +
  scale_x_continuous(breaks = seq(min(cell_lineage_stats_major$t), max(cell_lineage_stats_major$t), by = 1), labels=sort(unique(cell_lineage_stats_major$Timepoint))) +
  scale_color_manual(values = levels(cell_lineage_stats_major$Cell_type_broad_color)) +
  #scale_y_continuous(breaks = seq(0.4, 0.6, by = 0.02)) +
  theme_classic() +
  ylab("Phastcons placentals (distal CREs, 160 Mya)") +
    xlab("Developmental stage") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank())

wilcox.test(cell.stats$mean_phastcons_Placental_dist_160[cell.stats$Timepoint=="P63" & cell.stats$Cell_type_broad=="Astroglia"], cell.stats$mean_phastcons_Placental_dist_160[cell.stats$Timepoint=="P63" & cell.stats$Cell_type_broad!="Astroglia"])

p

pdf("~/Mouse_Cereb/Revisions/Figures/007_Mouse_cerebellum_CellTypesBroad_distal_160Mya_phastCons_Placentals.pdf", width = 6, height = 4, useDingbats = F); print(p); dev.off()
```


```{r}
p <- ggplot(filter(cell_lineage_stats_major, count >=50), aes(x=t, y= phastcons_Placental_dist_312_ci_mean, color=Cell_type_broad)) +
  geom_pointrange(aes(ymin=phastcons_Placental_dist_312_ci_low, ymax= phastcons_Placental_dist_312_ci_up)) +
  geom_line() +
  scale_x_continuous(breaks = seq(min(cell_lineage_stats_major$t), max(cell_lineage_stats_major$t), by = 1), labels=sort(unique(cell_lineage_stats_major$Timepoint))) +
  scale_color_manual(values = levels(cell_lineage_stats_major$Cell_type_broad_color)) +
  #scale_y_continuous(breaks = seq(0.4, 0.6, by = 0.02)) +
  theme_classic() +
  ylab("Phastcons placentals (distal CREs, 312 Mya)") +
    xlab("Developmental stage") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank())

p

pdf("~/Mouse_Cereb/Revisions/Figures/007_Mouse_cerebellum_CellTypesBroad_distal_312Mya_phastCons_Placentals.pdf", width = 6, height = 4, useDingbats = F); print(p); dev.off()
```

```{r}
sessionInfo()
```

